name: dart_flutter_demo
description: A Flutter UI showcase PoC app.
publish_to: 'none'
version: 0.5.0-beta.12+20260802

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  file_selector: ^1.1.0
  google_fonts: ^6.1.0
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.5
  system_info_vincentzyu:
    path: packages/system_info_vincentzyu
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mahiro-pfp-VincentZyu-square.png
    - assets/images/mahiro-pfp-VincentZyuApps-square.png
    - assets/images/mahiro-pfp-VincentZyu.jpg
    - assets/images/logo-icon-favicon.png
