#!/usr/bin/env python3
"""Generate an animated SVG card showing tracked language size distribution."""

from __future__ import annotations

import base64
import io
import subprocess
from collections import defaultdict
from datetime import datetime, timezone
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "doc" / "lang-stats.svg"
FONT_PATH = ROOT / "assets" / "fonts" / "LXGWWenKaiMono-Regular.ttf"

LANGUAGE_BY_SUFFIX = {
    ".dart": "Dart",
    ".kt": "Kotlin",
    ".swift": "Swift",
    ".cpp": "C++",
    ".cc": "C++",
    ".cxx": "C++",
    ".c": "C",
    ".h": "C Header",
    ".hpp": "C++ Header",
    ".py": "Python",
}

LANGUAGE_BY_NAME = {
    "CMakeLists.txt": "CMake",
}

LANG_COLORS = {
    "Dart": "#00B4AB",
    "Kotlin": "#A97BFF",
    "Swift": "#F05138",
    "C++": "#F34B7D",
    "C": "#555555",
    "C Header": "#708090",
    "C++ Header": "#8E44AD",
    "Python": "#3572A5",
    "CMake": "#DA3434",
}

IGNORE_PARTS = {
    ".git",
    "assets/generated-icons",
    "doc/preview-pics",
    "tmp",
    "build",
    "dist",
}

SVG_WIDTH = 560
CARD_PADDING = 22
ROW_HEIGHT = 28
FONT_STACK = "'LXGW WenKai Mono', 'Segoe UI', 'Noto Sans', sans-serif"


def list_tracked_files() -> list[Path]:
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    paths: list[Path] = []
    for raw in result.stdout.splitlines():
        if not raw.strip():
            continue
        path = Path(raw)
        normalized = raw.replace("\\", "/")
        if any(part in normalized for part in IGNORE_PARTS):
            continue
        paths.append(path)
    return paths


def detect_language(path: Path) -> str | None:
    if path.name in LANGUAGE_BY_NAME:
        return LANGUAGE_BY_NAME[path.name]
    return LANGUAGE_BY_SUFFIX.get(path.suffix.lower())


def count_bytes() -> dict[str, int]:
    stats: dict[str, int] = defaultdict(int)
    for rel_path in list_tracked_files():
        lang = detect_language(rel_path)
        if not lang:
            continue
        abs_path = ROOT / rel_path
        if not abs_path.is_file():
            continue
        stats[lang] += abs_path.stat().st_size
    return dict(sorted(stats.items(), key=lambda item: item[1], reverse=True))


def format_bytes(num_bytes: int) -> str:
    if num_bytes >= 1_000_000:
        return f"{num_bytes / 1_000_000:.2f} MB"
    if num_bytes >= 1_000:
        return f"{num_bytes / 1_000:.1f} KB"
    return f"{num_bytes} B"


def build_font_face_css() -> str:
    if not FONT_PATH.exists():
        return ""

    try:
        from fontTools.subset import Subsetter
        from fontTools.ttLib import TTFont
    except ImportError:
        print("fontTools not installed; using fallback fonts only.")
        return ""

    # Keep the subset narrow so the generated SVG stays small enough for README usage.
    text = (
        "📊 dart-flutter-demo · Language Footprint"
        "Tracked source bytes: Scope: git-tracked code, scripts, workflow docs, and build config"
        "Updated: Generated by scripts/generate_lang_stats.py"
        "DartPythonC++SwiftKotlinCMakeC Header"
        "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
        " .,:/%()-+"
    )

    font = TTFont(str(FONT_PATH))
    subsetter = Subsetter()
    subsetter.populate(text=text)
    subsetter.subset(font)

    buffer = io.BytesIO()
    font.flavor = "woff2"
    font.save(buffer)
    font.close()
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return f"""
    @font-face {{
      font-family: 'LXGW WenKai Mono';
      font-style: normal;
      font-weight: 400;
      src: url(data:font/woff2;base64,{encoded}) format('woff2');
    }}
    @font-face {{
      font-family: 'LXGW WenKai Mono';
      font-style: normal;
      font-weight: 600;
      src: url(data:font/woff2;base64,{encoded}) format('woff2');
    }}
    @font-face {{
      font-family: 'LXGW WenKai Mono';
      font-style: normal;
      font-weight: 700;
      src: url(data:font/woff2;base64,{encoded}) format('woff2');
    }}"""


def build_svg(stats: dict[str, int]) -> str:
    total = sum(stats.values())
    if total <= 0:
        raise RuntimeError("No tracked language bytes found.")

    top_bar_y = 92
    top_bar_h = 12
    table_start_y = 124
    footer_y = table_start_y + len(stats) * ROW_HEIGHT + 22
    height = footer_y + 16
    progress_x = 132
    progress_w = SVG_WIDTH - progress_x - 56
    percent_x = progress_x + progress_w + 10
    font_face_css = build_font_face_css()

    parts: list[str] = []
    parts.append(
        f"""<svg xmlns="http://www.w3.org/2000/svg" width="{SVG_WIDTH}" height="{height}" viewBox="0 0 {SVG_WIDTH} {height}">
<defs>
  <style>
{font_face_css}
    .bg {{ fill: #0f172a; }}
    .panel {{ fill: #111827; stroke: #1f2937; stroke-width: 1; }}
    .title {{ font: 700 18px {FONT_STACK}; fill: #e5f0ff; }}
    .sub {{ font: 400 11px {FONT_STACK}; fill: #94a3b8; }}
    .label {{ font: 600 12px {FONT_STACK}; fill: #e5e7eb; }}
    .meta {{ font: 400 11px {FONT_STACK}; fill: #94a3b8; }}
    .inbar {{ font: 700 11px {FONT_STACK}; fill: #f8fafc; stroke: rgba(15, 23, 42, 0.78); stroke-width: 2.2px; paint-order: stroke fill; stroke-linejoin: round; }}
    .barbg {{ fill: #1f2937; }}
    .row {{ opacity: 0; animation: fadeIn 0.55s ease forwards; }}
    .head {{ opacity: 0; animation: dropIn 0.7s ease forwards; }}
    @keyframes fadeIn {{ from {{ opacity: 0; transform: translateX(-8px); }} to {{ opacity: 1; transform: translateX(0); }} }}
    @keyframes dropIn {{ from {{ opacity: 0; transform: translateY(-8px); }} to {{ opacity: 1; transform: translateY(0); }} }}
  </style>
  <clipPath id="topbar-clip">
    <rect x="{CARD_PADDING}" y="{top_bar_y}" width="{SVG_WIDTH - CARD_PADDING * 2}" height="{top_bar_h}" rx="6"/>
  </clipPath>
</defs>
<rect class="bg" width="{SVG_WIDTH}" height="{height}" rx="16"/>
<rect class="panel" x="1" y="1" width="{SVG_WIDTH - 2}" height="{height - 2}" rx="15"/>
<text class="title head" x="{CARD_PADDING}" y="32">📊 dart-flutter-demo · Language Footprint</text>
<text class="sub head" x="{CARD_PADDING}" y="50" style="animation-delay:0.1s">Tracked source bytes: {format_bytes(total)} ({total:,} bytes)</text>
<text class="sub head" x="{CARD_PADDING}" y="66" style="animation-delay:0.2s">Scope: git-tracked code, scripts, workflow docs, and build config</text>
<text class="sub head" x="{CARD_PADDING}" y="82" style="animation-delay:0.3s">Updated: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")} UTC</text>
<rect class="barbg" x="{CARD_PADDING}" y="{top_bar_y}" width="{SVG_WIDTH - CARD_PADDING * 2}" height="{top_bar_h}" rx="6"/>
<g clip-path="url(#topbar-clip)">
"""
    )

    current_x = float(CARD_PADDING)
    total_bar_w = SVG_WIDTH - CARD_PADDING * 2
    for index, (lang, size) in enumerate(stats.items()):
        width = total_bar_w * (size / total)
        color = LANG_COLORS.get(lang, "#60a5fa")
        begin = 0.25 + index * 0.06
        parts.append(
            f"""<rect x="{current_x:.2f}" y="{top_bar_y}" width="0" height="{top_bar_h}" fill="{color}">
  <animate attributeName="width" from="0" to="{width:.2f}" dur="0.7s" begin="{begin:.2f}s" fill="freeze"/>
</rect>
"""
        )
        current_x += width

    parts.append("</g>\n")

    max_size = max(stats.values())
    for index, (lang, size) in enumerate(stats.items()):
        y = table_start_y + index * ROW_HEIGHT
        pct = size / total * 100
        fill_w = max(progress_w * (size / max_size), 1.0)
        color = LANG_COLORS.get(lang, "#60a5fa")
        delay = 0.35 + index * 0.08
        parts.append(
            f"""<g class="row" style="animation-delay:{delay:.2f}s">
  <circle cx="26" cy="{y + 8}" r="5" fill="{color}"/>
  <text class="label" x="38" y="{y + 12}">{escape(lang)}</text>
  <rect class="barbg" x="{progress_x}" y="{y}" width="{progress_w}" height="15" rx="7"/>
  <rect x="{progress_x}" y="{y}" width="0" height="15" rx="7" fill="{color}" opacity="0.92">
    <animate attributeName="width" from="0" to="{fill_w:.2f}" dur="0.8s" begin="{delay:.2f}s" fill="freeze"/>
  </rect>
  <text class="inbar" x="{progress_x + 8}" y="{y + 12}">{format_bytes(size)}</text>
  <text class="meta" x="{percent_x}" y="{y + 12}">{pct:.1f}%</text>
</g>
"""
        )

    parts.append(
        f"""<text class="sub" x="{SVG_WIDTH - CARD_PADDING}" y="{footer_y}" text-anchor="end">Generated by scripts/generate_lang_stats.py</text>
</svg>
"""
    )
    return "".join(parts)


def main() -> None:
    stats = count_bytes()
    svg = build_svg(stats)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(svg, encoding="utf-8")
    print(f"Generated {OUTPUT}")
    total = sum(stats.values())
    for lang, size in stats.items():
        print(f"{lang:>10}: {size:>8} bytes ({size / total * 100:5.1f}%)")


if __name__ == "__main__":
    main()
