display_name: DartFlutterDemo
package_name: dart-flutter-demo-showcase
maintainer:
  name: VincentZyu
  email: 1830540513zyu@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/logo-icon-favicon.png

keywords:
  - Dart
  - Flutter
  - Demo

generic_name: DartFlutterDemo

categories:
  - Development
  - Utility

startup_notify: true

# Lets the dock or taskbar match the running GTK window with this entry.
startup_wm_class: io.github.vincentzyuapps.dartflutterdemo
